name: Run WebDriverIO Tests with Appium
on:
  pull_request:
    branches: [main]
  workflow_dispatch: # Enables manual trigger

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Android SDK Dependencies
        run: |
          # Install required dependencies
          sudo apt update
          manager --update

      - name: Set up Android Emulator
        run: |
          # Create AVD (if it doesn't exist)
          echo "Creating Android Emulator..."
          echo no | avdmanager create avd -n Pixel_4_API_33 -k "system-images;android-33;google_apis;x86_64" --force

      - name: Start Android Emulator
        run: |
          echo "Starting the Android Emulator..."
          nohup emulator -avd Pixel_4_API_33 -no-window -gpu off &
          adb wait-for-device
          adb devices
          sleep 30 # Wait for emulator to fully start

      - name: Install Dependencies
        run: |
          npm ci # Install dependencies defined in package-lock.json
          npm install --save-dev appium wdio-appium-service allure-commandline

      - name: Download APK from GitHub Release
        run: |
          curl -L -o WikipediaSample.apk https://github.com/Aishwarya-U-R/SoarInc_E2EMobileAutomation/releases/download/v1.0/WikipediaSample.apk

      - name: Set APK_PATH environment variable
        run: echo "APK_PATH=/tmp/WikipediaSample.apk" >> $GITHUB_ENV

      - name: Start Appium Server
        run: |
          nohup npx appium &

      - name: Run WebDriverIO Tests
        run: |
          npx wdio run wdio.conf.ts

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: ./allure-report # Path where the HTML report is generated
